# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'servLynk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for servLynk

  target 'servLynk-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'servLynkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Required by RNFirebase
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Auth'
pod 'Firebase/Database'