fastlane_version "2.112.0"
generated_fastfile_id "a4ac21cd-f236-4603-97cf-5ae088d5d329"

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
  # iOS Lanes
  desc "Fetch certificates and provisioning profiles"
  lane :certificates do
    match(app_identifier: "com.app.bundle", type: "development", readonly: true)
    match(app_identifier: "com.app.bundle", type: "appstore", readonly: true)
  end

  desc "Build the iOS application."
  private_lane :build do
    certificates
    increment_build_number(xcodeproj: "./ios/name.xcodeproj")
    gym(scheme: "name", project: "./ios/name.xcodeproj")
  end

  desc "Ship to Testflight."
  lane :beta do
    build
    pilot
    commit_version_bump(message: "Bump build", xcodeproj: "./ios/name.xcodeproj")
    push_to_git_remote
  end
end

platform :android do
  # Android Lanes
  desc "Build the Android application."
  private_lane :build do
    gradle(task: "clean", project_dir: "android/")
    gradle(task: "assemble", build_type: "Release", project_dir: "android/")
  end

  desc "Build the Android debug application."
  private_lane :debug do
    gradle(task: "clean", project_dir: "android/")
    gradle(task: "assemble", build_type: "Debug", project_dir: "android/")
  end

  desc "Ship to Playstore Beta."
  lane :beta do
    debug
    crashlytics(
      api_token: "7ecb17ebc2b5f95c4b1a62a6c1044c8309320e5d",
      build_secret: "c18b5deadc6b049572043c20c684433946ff4f9b711aa137b2129692798b4856"
    )
  end
end
